### ISSUE TITLE
Is walkinafog open source?

### ISSUE THREAD

**Issue by intgr** [idflood/walkinafog.com#2]
Putting up source code on GitHub seems like an intent to open source the project. However, the project is not currently accompanied by an open source license. Did I commit a felony when I cloned this project? Please add a license file :)

**Comment by idflood** [comment]
Ohh yeah, It's definitely open source. I'm hesitating between MIT license and creative common, I will have to document myself about this. The special case is about the music, I don't know if it can be embedded inside an opensource project or not, and how to specify the license of it.

I will ask the producer about it, but if you have a suggestion don't hesitate.

**Comment by intgr** [comment]
> The special case is about the music, I don't know if it can be embedded inside an opensource project or not

Evaldas Azbukauskas (SoulSonic) has previously licensed his music under CC licenses (e.g. there's a license grant at http://archive.org/details/Complex_798 and a few more of his earlier releases), so I figure he might be open to granting a license for this track, too.

The only problem with CC is that the "Noncommercial" and "No Derivative Works" clauses conflict with most peoples' understanding of open source -- better to avoid them if possible. But even that's better than no license. :)

> and how to specify the license of it.

Most projects simply have a LICENSE.txt or COPYING.txt in the root directory, that states which files/directories are covered by which license, followed by full copies of the license texts.

Example: https://gitweb.torproject.org/tor.git/blob_plain/HEAD:/LICENSE

**Comment by idflood** [comment]
I just uploaded a license file and decided to go for the MIT.
